sonar.projectKey=CIR_NG_WEB_APP_2026-2-
sonar.login=squ_aaf3faa1042a7b0170cbc4c55d1ff593d5d98ab6
sonar.sources=dist
sonar.scm.disabled=true
sonar.host.url=https://sonarq2.takeitsolution.com
sonar.token=sqp_3ffc39fd3426db3b43bc18f8492295ea7d682b1d
